var Maps = {};
var currentMapName = "";

Maps.getMap = function(mapName) {
	return maps[mapName];
};

Maps.getCurrentMapName = function() {
	return currentMapName;
};

Maps.setCurrentMap = function(mapName) {
	currentMapName = mapName;
};

Maps.getCurrentMap = function() {
	return maps[currentMapName];
};

Maps.getAllMapNames = function() {
	return Object.keys(maps);
};

Maps.getLinkingLocation = function(mapName, location) {
	var result = mapLinks[mapName][location.row + "-" + location.col];
	return {mapName: result.mapName, location: {row: result.location.row, col: result.location.col}}
};

Maps.getTestStartLocation = function(mapName) {
	return {row: 6, col: 5};
};

Maps.getRandomLevelForCurrentMap = function() {
	var range = mapLevels[Maps.getCurrentMapName()];
	return Math.floor(Math.random() * (range.endLevel - range.startLevel + 1)) + range.startLevel;
};

Maps.getRandomPokemonForCurrentMap = function() {
	var mapValues = pokemonEncounters[Maps.getCurrentMapName()];
	var listOfPokemon = Object.keys(mapValues);
	var rand = Math.random();

	var j = 0;
	for (var i = 0; i < listOfPokemon.length; i++) {
		j += mapValues[listOfPokemon[i]];
		if (rand < j) {
			var resource = PokemonResource.getByResourceUri("/api/v1/pokemon/" + listOfPokemon[i] + "/");
			var level = Maps.getRandomLevelForCurrentMap();
			return new Pokemon(resource, level, Move.getDefaultMovesForPokemon(resource, level), null);
		}
	}
};

var mapLinks = {
	"PalletTown": {
		"0-10": {
			mapName: "Route1",
			location: {
				row: 35,
				col: 7
			}
		},
		"0-11": {
			mapName: "Route1",
			location: {
				row: 35,
				col: 8
			}
		},
		"17-4": {
		
		},
		"17-5": {
			
		},
		"17-6": {
			
		},
		"17-7": {
			
		}
	},
	"Route1": {
		"35-7": {
			mapName: "PalletTown",
			location: {
				row: 0,
				col: 10
			}
		},
		"35-8": {
			mapName: "PalletTown",
			location: {
				row: 0,
				col: 11
			}
		},
		"0-7": {
			mapName: "VeridianCity",
			location: {
				row: 35,
				col: 28
			}
		},
		"0-8": {
			mapName: "VeridianCity",
			location: {
				row: 35,
				col: 29
			}
		}
	},
	"ViridianCity": {
		"35-28": {
			mapName: "Route1",
			location: {
				row: 0,
				col: 7
			}
		},
		"35-29": {
			mapName: "Route1",
			location: {
				row: 0,
				col: 8
			}
		}
	}
};

var maps = {
	PalletTown: [
		['groundYellow', 'groundYellow', 'groundYellow', 'cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'cylinderBarrier', 'grass', 'grass', 'cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'cylinderBarrier', 'groundYellow'],
		['cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'grass', 'grass', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundWhite', 'groundWhite', 'buildingGreenTall00', 'buildingGreenTall01', 'buildingGreenTall01', 'buildingGreenTall03', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingGreenTall00', 'buildingGreenTall01', 'buildingGreenTall01', 'buildingGreenTall03', 'groundWhite', 'groundWhite', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundWhite', 'groundWhite', 'buildingGreenTall10', 'buildingGreenTall11', 'buildingGreenTall12', 'buildingGreenTall13', 'groundWhite', 'groundWhite', 'groundYellow', 'groundYellow', 'buildingGreenTall10', 'buildingGreenTall11', 'buildingGreenTall12', 'buildingGreenTall13', 'groundWhite', 'groundWhite', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundWhite', 'signWhite', 'buildingGreenTall20', 'door', 'buildingGreenTall22', 'buildingGreenTall23', 'groundWhite', 'groundWhite', 'groundYellow', 'signWhite', 'buildingGreenTall20', 'door', 'buildingGreenTall22', 'buildingGreenTall23', 'groundWhite', 'groundWhite', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingBrickTall00', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall05', 'groundWhite', 'groundWhite', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundWhite', 'groundWhite', 'fence', 'fence', 'fence', 'signWhite', 'groundWhite', 'groundWhite', 'buildingBrickTall10', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall15', 'groundWhite', 'groundWhite', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundWhite', 'groundWhite', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundWhite', 'groundWhite', 'buildingBrickTall20', 'buildingBrickTall21', 'buildingBrickTall22', 'buildingBrickTall23', 'buildingBrickTall24', 'buildingBrickTall25', 'groundWhite', 'groundWhite', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundWhite', 'groundWhite', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundWhite', 'groundWhite', 'buildingBrickTall30', 'buildingBrickTall31', 'door', 'buildingBrickTall33', 'buildingBrickTall31', 'buildingBrickTall35', 'groundWhite', 'groundWhite', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'fence', 'fence', 'fence', 'signWhite', 'fence', 'fence', 'groundWhite', 'groundWhite', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'waterTopLeft', 'waterTop', 'waterTop', 'waterTopRight', 'groundWhite', 'groundWhite', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundWhite', 'groundWhite', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'waterLeft', 'water', 'water', 'waterRight', 'groundWhite', 'groundWhite', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundWhite', 'groundWhite', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'waterLeft', 'water', 'water', 'waterRight', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'waterLeft', 'water', 'water', 'waterRight', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier']
	],
	Route1: [
		['cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'cylinderBarrier', 'groundYellow', 'groundYellow', 'cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'groundYellow', 'groundYellow', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'smallTree', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'cylinderBarrier'],
		['smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'smallTree'],
		['smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'smallTree'],
		['smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'smallTree'],
		['smallTree', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'smallTree', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'smallTree'],
		['smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree'],
		['smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree'],
		['smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'grass', 'grass', 'grass', 'grass', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'grass', 'grass', 'grass', 'grass', 'smallTree'],
		['cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'grass', 'grass', 'grass', 'grass', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'grass', 'grass', 'grass', 'grass', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'grass', 'grass', 'grass', 'grass', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'cliffDown', 'groundYellow', 'cliffDown', 'cliffDown', 'cliffDown', 'groundYellow', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'grass', 'grass', 'grass', 'grass', 'groundYellow', 'groundYellow', 'cylinderBarrier'],
		['cylinderBarrier', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'grass', 'grass', 'grass', 'grass', 'cliffDown', 'cliffDown', 'cylinderBarrier'],
		['smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'grass', 'grass', 'grass', 'grass', 'groundYellow', 'groundYellow', 'smallTree'],
		['smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'grass', 'grass', 'grass', 'grass', 'groundYellow', 'groundYellow', 'smallTree'],
		['smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree'],
		['smallTree', 'cliffDown', 'cliffDown', 'groundYellow', 'groundYellow', 'groundYellow', 'signYellow', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'smallTree'],
		['smallTree', 'groundYellow', 'groundYellow', 'grass', 'grass', 'grass', 'grass', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'grass', 'grass', 'grass', 'grass', 'smallTree'],
		['smallTree', 'groundYellow', 'groundYellow', 'grass', 'grass', 'grass', 'grass', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'grass', 'grass', 'grass', 'grass', 'smallTree'],
		['smallTree', 'grass', 'grass', 'grass', 'grass', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'grass', 'grass', 'grass', 'grass', 'groundYellow', 'groundYellow', 'smallTree'],
		['smallTree', 'grass', 'grass', 'grass', 'grass', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'grass', 'grass', 'grass', 'grass', 'groundYellow', 'groundYellow', 'smallTree'],
		['smallTree', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'grass', 'grass', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'smallTree'],
		['smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'cylinderBarrier', 'grass', 'grass', 'cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree'],
		['smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'cylinderBarrier', 'grass', 'grass', 'cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree'],
		['smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'cylinderBarrier', 'grass', 'grass', 'cylinderBarrier', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree']
	],
	ViridianCity: [
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'fence', 'groundWhite', 'groundWhite', 'signYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingGreenShort00', 'buildingGreenShort01', 'buildingGreenShort01', 'buildingGreenShort03', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingGym00', 'buildingGym01', 'buildingGym01', 'buildingGym01', 'buildingGym01', 'buildingGym05', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundGreen', 'groundGreen', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'smallTree', 'smallTree', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingGreenShort10', 'buildingGreenShort12', 'buildingGreenShort12', 'buildingGreenShort13', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingGym10', 'buildingGym11', 'buildingGym11', 'buildingGym11', 'buildingGym11', 'buildingGym15', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundGreen', 'cylinderBarrier', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingGym20', 'buildingGym21', 'buildingGym22', 'buildingGym23', 'buildingGym21', 'buildingGym25', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundGreen', 'cylinderBarrier', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'signYellow', 'buildingGym30', 'buildingGym31', 'buildingGym31', 'buildingGym31', 'door', 'buildingGym35', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundGreen', 'cylinderBarrier', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingGreenShort00', 'buildingGreenShort01', 'buildingGreenShort01', 'buildingGreenShort03', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundGreen', 'cylinderBarrier', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingGreenShort10', 'door', 'buildingGreenShort12', 'buildingGreenShort13', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundGreen', 'cylinderBarrier', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundGreen', 'cylinderBarrier', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundGreen', 'cylinderBarrier', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingBrickTall00', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall05', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainBottom', 'mountainBottom', 'mountainBottom', 'mountainBottom', 'mountainBottom', 'mountainBottomRight', 'groundGreen', 'cylinderBarrier', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingBrickTall10', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall15', 'groundWhite', 'groundWhite', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'cylinderBarrier', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingBrickTall20', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall25', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'cylinderBarrier', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'signYellow', 'buildingBrickTall30', 'door', 'buildingBrickTall31', 'buildingBrickTall31', 'buildingBrickTall31', 'buildingBrickTall35', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingBrickTall00', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall05', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'signYellow', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingBrickTall10', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall15', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainTop', 'mountainTop', 'mountainTop', 'mountainTopRight', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'buildingBrickTall20', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall25', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'buildingBrickTall30', 'door', 'signPokeMart', 'buildingBrickTall35', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'buildingBrickTall00', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall05', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'buildingBrickTall10', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall15', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'waterTopLeft', 'waterTop', 'waterTop', 'waterTop', 'waterTop', 'waterTopRight', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'buildingBrickTall20', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall25', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'waterLeft', 'water', 'water', 'water', 'water', 'waterRight', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'buildingBrickTall30', 'door', 'signPokeCenter', 'buildingBrickTall35', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'waterLeft', 'water', 'water', 'water', 'water', 'waterRight', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'waterLeft', 'water', 'water', 'water', 'water', 'waterRight', 'cliffDown', 'groundGreen', 'cliffDown', 'cliffDown', 'cliffDown', 'groundGreen', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainBottom', 'mountainBottom', 'mountainBottom', 'mountainBottomRight', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'groundWhite', 'groundWhite', 'fence', 'fence', 'fence', 'fence', 'fence', 'fence', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'cylinderBarrier', 'groundWhite', 'groundWhite', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen'],
		['groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'cylinderBarrier', 'groundWhite', 'groundWhite', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen'],
		['groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'cylinderBarrier', 'groundWhite', 'groundWhite', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen'],
		['groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'cylinderBarrier', 'groundWhite', 'groundWhite', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen']
	],
	Route2: [
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'groundWhite', 'groundWhite', 'fence', 'groundWhite', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'groundWhite', 'groundWhite', 'fence', 'groundWhite', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'groundWhite', 'groundWhite', 'fence', 'groundWhite', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'groundWhite', 'groundWhite', 'fence', 'groundWhite', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'groundWhite', 'groundWhite', 'mountainTopLeft', 'mountainTop', 'mountainTop', 'mountainTop', 'mountainTop', 'mountainTop', 'mountainTop', 'mountainTopRight', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'groundWhite', 'groundWhite', 'mountainLeft', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'mountainLeft', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'mountainBottomLeft', 'mountainRight', 'mountainRight', 'mountainRight', 'mountainRight', 'mountainRight', 'mountainRight', 'mountainBottomRight', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'smallTree', '', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'smallTree', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundYellow', 'signYellow', 'groundYellow', 'groundYellow', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'buildingBrickTall00', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall05', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'buildingBrickTall10', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall15', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'buildingBrickTall20', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall25', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'cylinderBarrier', 'cylinderBarrier', 'buildingBrickTall30', 'door', 'buildingBrickTall31', 'buildingBrickTall35', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'buildingGreenShort00', 'buildingGreenShort01', 'buildingGreenShort01', 'buildingGreenShort03', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'buildingGreenShort10', 'door', 'buildingGreenShort12', 'buildingGreenShort13', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'grass', 'grass', 'groundWhite', 'groundWhite', 'grass', 'grass', 'grass', 'grass', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'grass', 'grass', 'groundWhite', 'groundWhite', 'grass', 'grass', 'grass', 'grass', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', '', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffPassage', 'cliffDown', 'cliffDown', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffPassage', 'cliffDown', 'cliffDown', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'cylinderBarrier', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'cylinderBarrier', 'cylinderBarrier', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'buildingBrickTall00', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall05', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'buildingBrickTall10', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall15', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'smallTree', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'buildingBrickTall20', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall25', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'smallTree', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'buildingBrickTall30', 'door', 'buildingBrickTall31', 'buildingBrickTall31', 'buildingBrickTall31', 'buildingBrickTall35', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'buildingBrickTall00', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall05', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'buildingBrickTall10', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall15', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'buildingBrickTall20', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall25', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'cliffDown', 'cliffPassage', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'cylinderBarrier', 'cylinderBarrier', 'buildingBrickTall30', 'door', 'buildingBrickTall31', 'buildingBrickTall35', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundBrick', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'groundYellow', 'groundYellow', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'groundGreen', 'smallTree', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffPassage', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', '', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffPassage', 'cliffDown', 'cliffDown', 'cliffDown', 'smallTree', 'smallTree', 'smallTree', 'cliffDown', 'cliffPassage', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree']
	],
	PewterCity: [
		['groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainTop', 'mountainTop', 'mountainTop', 'mountainTopRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'buildingGym00', 'buildingGym01', 'buildingGym01', 'buildingGym01', 'buildingGym01', 'buildingGym01', 'buildingGym01', 'buildingGym05', 'buildingBrickTall00', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall05', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'buildingGym10', 'buildingGym11', 'buildingGym11', 'buildingGym11', 'buildingGym11', 'buildingGym11', 'buildingGym11', 'buildingGym15', 'buildingBrickTall10', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall15', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'buildingGym10', 'buildingGym11', 'buildingGym11', 'buildingGym11', 'buildingGym11', 'buildingGym11', 'buildingGym11', 'buildingGym15', 'buildingBrickTall20', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall25', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'buildingGym20', 'buildingBrickTall24', 'buildingBrickTall24', 'buildingBrickTall24', 'buildingBrickTall24', 'buildingBrickTall24', 'buildingBrickTall24', 'buildingGym25', 'buildingBrickTall30', 'buildingBrickTall31', 'buildingBrickTall31', 'buildingBrickTall31', 'buildingBrickTall31', 'buildingBrickTall35', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'buildingBrickTall20', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall25', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffPassage', 'cliffDown', 'cliffDown', 'buildingBrickTall30', 'buildingBrickTall31', 'buildingBrickTall31', 'buildingBrickTall31', 'buildingBrickTall31', 'buildingBrickTall31', 'buildingBrickTall31', 'buildingBrickTall35', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffPassage', 'cliffDown', 'cliffDown', 'cliffDown', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'signYellow', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'mountainTopLeft', 'mountainTop', 'mountainTop', 'mountainTop', 'mountainTop', 'mountainTop'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'mountainLeft', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'buildingGreenShort00', 'buildingGreenShort01', 'buildingGreenShort01', 'buildingGreenShort03', 'groundWhite', 'groundWhite', 'mountainLeft', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'buildingGreenShort10', 'door', 'buildingGreenShort12', 'buildingGreenShort13', 'groundWhite', 'groundWhite', 'mountainLeft', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'buildingGym00', 'buildingGym01', 'buildingGym01', 'buildingGym01', 'buildingGym01', 'buildingGym05', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingBrickTall00', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall05', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'mountainLeft', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'buildingGym10', 'buildingGym11', 'buildingGym11', 'buildingGym11', 'buildingGym11', 'buildingGym15', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingBrickTall10', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall15', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'mountainBottomLeft', 'mountainBottom', 'mountainBottom', 'mountainBottom', 'mountainBottom', 'mountainBottom'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'buildingGym20', 'buildingGym21', 'buildingGym22', 'buildingGym23', 'buildingGym21', 'buildingGym25', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'buildingBrickTall20', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall25', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'signYellow', 'buildingGym30', 'buildingGym31', 'buildingGym31', 'buildingGym31', 'door', 'buildingGym35', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'buildingBrickTall30', 'door', 'signPokeMart', 'buildingBrickTall35', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'signYellow', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'fence', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'mountainTopLeft', 'mountainTop', 'mountainTop', 'mountainTop', 'mountainTop', 'mountainTop'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'fence', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'mountainLeft', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingBrickTall00', 'buildingBrickTall01', 'buildingBrickTall01', 'buildingBrickTall05', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'mountainLeft', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'buildingBrickTall10', 'buildingBrickTall11', 'buildingBrickTall11', 'buildingBrickTall15', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'fence', 'fence', 'fence', 'signYellow', 'fence', 'fence', 'fence', 'fence', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'mountainLeft', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'buildingBrickTall20', 'buildingBrickTall21', 'buildingBrickTall21', 'buildingBrickTall25', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'groundGreen', 'groundWhite', 'groundWhite', 'mountainLeft', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainCenter'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'buildingBrickTall30', 'door', 'signPokeCenter', 'buildingBrickTall35', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'groundGreen', 'groundWhite', 'groundWhite', 'mountainBottomLeft', 'mountainBottom', 'mountainBottom', 'mountainBottom', 'mountainBottom', 'mountainBottom'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen'],
		['mountainCenter', 'mountainCenter', 'mountainCenter', 'mountainRight', 'groundWhite', 'groundWhite', 'buildingGreenShort00', 'buildingGreenShort01', 'buildingGreenShort01', 'buildingGreenShort03', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'smallTree', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'groundYellow', 'smallTree', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen'],
		['mountainCenter', 'mountainInnerBottomRight', 'mountainBottom', 'mountainBottomRight', 'groundWhite', 'groundWhite', 'buildingGreenShort10', 'door', 'buildingGreenShort12', 'buildingGreenShort13', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundWhite', 'signYellow', 'groundGreen', 'smallTree', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffPassage', 'cliffDown', 'cliffDown', 'cliffDown', 'cliffDown', 'smallTree', 'groundGreen', 'groundWhite', 'groundWhite', 'groundGreen', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen'],
		['mountainCenter', 'mountainRight', 'cylinderBarrier', 'cylinderBarrier', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen'],
		['mountainCenter', 'mountainRight', 'cylinderBarrier', 'cylinderBarrier', 'groundWhite', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundWhite', 'groundGreen', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen'],
		['mountainCenter', 'mountainRight', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'cylinderBarrier', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen'],
		['mountainBottom', 'mountainBottomRight', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen'],
		['groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen'],
		['groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundWhite', 'groundWhite', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'smallTree', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen', 'groundGreen']
	]
};

var mapLevels = {
	"PalletTown": new LevelRange(2, 4),
	"Route1": new LevelRange(2, 5),
	"ViridianCity": new LevelRange(3, 6),
	"Route2": new LevelRange(4, 8)
};

var pokemonEncounters = {
	"PalletTown": {16:.55, 19:.45},
	"Route1": {16:.55, 19:.45},
	"ViridianCity": {},
	"Route22": {19:.10, 21:.10, 56:.20, 29:.30, 32:.30},
	"Route2": {19:.40, 16:.30, 29:.15, 32:.15},
	"ViridianForest": {10:.55, 11:.20, 16:.24, 17:.01},
	"PewterCity": {},
	"Route3": {21:.55, 19:.15, 27:.15, 56:.15},
	"MtMoon1": {41:.75, 74:.20, 35:.01, 27:.04},
	"MtMoon2": {41:.65, 74:.20, 46:.10, 35:.05},
	"MtMoon3": {41:.60, 74:.15, 46:.15, 35:.10},
	"Route4": {19:.15, 21:.55, 27:.15, 56:.15},
	"CeruleanCity": {},
	"Route24": {69:.25, 48:.10, 16:.29, 17:.01, 43:.35},
	"Route25": {16:.29, 17:.01, 43:.30, 69:.30, 48:.10},
	"Route5": {16:.45, 17:.05, 19:.25, 39:.10, 63:.15},
	"Route6": {16:.45, 17:.05, 19:.25, 39:.10, 63:.15},
	"VermillionCity": {},
	"S.S.Anne": {},
	"Route11": {96:.24, 16:.40, 17:.10, 19:.25, 20:.01},
	"DiglettsCave": {50:.95, 51:.05},
	"Route9": {21:.10, 22:.01, 19:.15, 20:.04, 32:.35, 33:.05, 29:.25, 30:.05},
	"Route10": {19:.15, 20:.05, 32:.10, 35:.10, 66:.05, 81:.55},
	"RockTunnel1": {41:.55, 74:.35, 66:.10},
	"RockTunnel2": {41:.45, 74:.25, 66:.20, 95:.10},
	"LavenderTown": {},
	"Route7": {16:.40, 17:.10, 19:.15, 39:.10, 63:.25},
	"Route8": {16:.40, 17:.10, 19:.15, 39:.10, 63:.20, 64:.05},
	"CeladonCity": {},
	"RocketHideout": {},
	"PokemonTower": {92:.90, 93:.05, 104:.05},
	"SaffronCity": {},
	"SilphCompany": {},
	"Route16": {19:.25, 20:.05, 21:.30, 22:.05, 84:.35},
	"Route17": {21:.30, 33:.20, 77:.24, 84:.25, 86:.01},
	"Route18": {19:.25, 20:.05, 21:.30, 22:.05, 84:.35},
	"FuchsiaCity": {},
	"SafariZone1": {29:.15, 32:.25, 33:.10, 102:.15, 46:.05, 47:.15, 111:.10, 113:.01, 114:.04},
	"SafariZone2": {29:.15, 30:.10, 32:.25, 102:.20, 113:.04, 123:.01, 128:.10, 104:.10, 105:.05},
	"SafariZone3": {29:.15, 30:.10, 32:.25, 102:.15, 111:.10, 123:.04, 127:.01, 115:.15, 104:.05},
	"SafariZone4": {29:.15, 32:.25, 33:.10, 102:.20, 127:.04, 128:.10, 104:.10, 105:.05, 114:.01},
	"Route12": {16:.15, 17:.10, 69:.25, 70:.05, 83:.05, 43:.35, 44:.05},
	"Route13": {16:.10, 17:.15, 69:.25, 70:.05, 83:.05, 43:.35, 44:.05},
	"Route14": {17:.10, 48:.19, 49:.01, 69:.25, 70:.05, 43:.35, 44:.05},
	"Route15": {17:.10, 48:.19, 49:.01, 69:.25, 70:.05, 43:.35, 44:.05},
	"Route21": {19:.25, 20:.05, 16:.60, 17:.10},
	"CinnabarIsland": {},
	"PokemonMansion1": {88:.20, 19:.35, 20:.25, 58:.20},
	"PokemonMansion2": {88:.35, 89:.05, 19:.35, 20:.25},
	"PokemonMansion3": {88:.35, 89:.05, 19:.35, 20:.25},
	"PokemonMansion4": {88:.40, 89:.10, 20:.40, 132:.10},
	"PowerPlant": {81:.40, 82:.20, 88:.15, 89:.05, 100:.20},
	"Route19": {},
	"Route20": {},
	"SeafoamIsland1": {41:.50, 42:.05, 79:.15, 98:.30},
	"SeafoamIsland2": {41:.45, 42:.10, 79:.10, 86:.05, 98:.25, 99:.05},
	"SeafoamIsland3": {41:.40, 42:.15, 79:.04, 80:.01, 86:.10, 98:.20, 99:.10},
	"SeafoamIsland4": {41:.25, 42:.25, 86:.15, 87:.05, 98:.20, 99:.10},
	"SeafoamIsland5": {41:.20, 42:.30, 86:.20, 87:.05, 98:.15, 99:.10},
	"Route23": {22:.15, 30:.25, 33:.35, 56:.20, 57:.05},
	"VictoryRoad1": {41:.10, 42:.10, 74:.55, 75:.10, 67:.05, 95:.10},
	"VictoryRoad2": {42:.15, 74:.50, 75:.15, 67:.10, 95:.10},
	"VictoryRoad3": {41:.20, 74:.65, 75:.05, 95:.10},
	"UnknownDungeon1": {28:.10, 42:.40, 44:.05, 70:.05, 75:.15, 111:.15, 112:.05, 132:.05},
	"UnknownDungeon2": {28:.10, 42:.40, 44:.10, 70:.10, 75:.15, 47:.05, 49:.05, 132:.05},
	"UnknownDungeon3": {42:.40, 75:.15, 132:.15, 111:.10, 112:.10, 113:.05, 108:.05}
};